### ISSUE TITLE
Documentation: Link leading to vignettes are not working 

### ISSUE THREAD

**Issue by sadchla-codes** [atorus-research/Tplyr#104]
### Prerequisites

For more information, see the `CONTRIBUTING` guide.

### Description
Link to the vignettes in table.Rmd are not working.
![table_rmd](https://user-images.githubusercontent.com/112789549/198855737-1a8273af-d584-4c25-9168-9959bda73d96.png)

### Versions

You can get this information from executing `sessionInfo()`.

**Comment by mstackhouse** [comment]
@sadchla-codes  this was closed in #100 right?

**Comment by sadchla-codes** [comment]
Hi Mike, this is a different issue, this one the links are not working and it might be because there is an `s` in `vignette`. I'm going to link it with https://github.com/atorus-research/Tplyr/issues/103#issue-1425797936 so they can be closed together
