### ISSUE TITLE
The ut_round() function rounds differently from SAS

### ISSUE THREAD

**Issue by alexhomel** [atorus-research/Tplyr#124]
### Description

The `ut_round()` function produces unexpected results with `options(tplyr.IBMRounding = TRUE)`.

https://github.com/atorus-research/Tplyr/blob/6876054d7e88b3638cf452dbaaba81a793b20ae0/R/utils.R#L313-L321

### Steps to Reproduce

Let's count the mean using a test vector and round it to 3 decimals using `ut_round()`:
```r
> vec <- c(2.64, -3.20, -2.88, 2.95)

> mvec <- mean(vec)

> mvec
[1] -0.1225

> ut_round(mvec, 3)
[1] -0.122
```

The expected value is -0.123 but I'm getting -0.122

**Comment by mstackhouse** [comment]
Closed via #126
