### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by asbates** [atorus-research/Tplyr#128]
I got the following warning when using `Tplyr`.

![image](https://github.com/atorus-research/Tplyr/assets/36482959/8b8628e8-1104-4cef-914f-10b1663dd4b5)

`forcats::fct_explicit_na` is deprecated and should be replaced with `forcats::fct_na_value_to_level`. This is only used in one place: https://github.com/atorus-research/Tplyr/blob/6876054d7e88b3638cf452dbaaba81a793b20ae0/R/count.R#L735. (and import statement in `zzz.R`)

- Tplyr version: 1.1.0
- dplyr version: 1.1.0
- forcats version: 1.0.0

**Comment by mstackhouse** [comment]
Closed via #139
