### ISSUE TITLE
Getting an error when i try to use the Tplyr for the table `adverse events by maximum severity`

### ISSUE THREAD

**Issue by jagadishkatam** [atorus-research/Tplyr#143]
I am trying to develop the adverse events by maximum severity table where i will be using the ADAE dataframe. I am taking the maximum severity values per USUBJID, AEDECOD and AESEV. If i pass the data into Tplyr as below 

```r
dt <- Tplyr::tplyr_table(adae, TRTA) %>% 
  set_pop_data(adsl) %>% 
  set_pop_treat_var(TRTA) %>% 
  set_pop_where(TRUE) %>% 
    Tplyr::add_layer(group_count(vars(AEDECOD,AESEV)) %>% 
                     set_format_strings(f_str("xxx (xx.x%)", distinct_n, distinct_pct))) %>% 
  set_distinct_by(USUBJID) %>% 
  add_total_group() %>%
  Tplyr::build() 
```
I get the error as below 

<img width="673" alt="image" src="https://github.com/atorus-research/Tplyr/assets/83913148/197a467c-3dca-48da-8c88-48913fb2af62">

to want to get the output as below 

<img width="118" alt="image" src="https://github.com/atorus-research/Tplyr/assets/83913148/c9302fc2-2a60-4891-b124-b2b558be6879">

any thoughts on how i can generate these type of tables using Tplyr

**Comment by mstackhouse** [comment]
Hi @jagadishkatam. I would suggest doing this using a by variable instead of a nested count layer. 

```r
dt <- tplyr_table(adae, TRTA) %>% 
  set_pop_data(adsl) %>% 
  set_pop_treat_var(TRTA) %>% 
  set_pop_where(TRUE) %>% 
  set_distinct_by(USUBJID) %>% 
  add_total_group() %>%
    add_layer(
      group_count(AEDECOD, by = AESEV) %>% 
        set_format_strings(f_str("xxx (xx.x%)", distinct_n, distinct_pct))
  ) %>% 
  build()
```

It's not going to give that exact presentation - but with #129 it would allow you to post process into this format. 

Does this help?

**Comment by jagadishkatam** [comment]
Thank you @mstackhouse for your prompt response, I tried your apporach of using `by` and it created the row_label1 and row_label2, now since i wanted to parse row_label1 and row_label2 , a post processing is followed. 

```r
dt <- Tplyr::tplyr_table(adae, TRTA) %>% 
  set_pop_data(adsl) %>% 
  set_pop_treat_var(TRTA) %>% 
  set_pop_where(TRUE) %>% 
  Tplyr::add_layer(group_count(AESEV, by=all) %>% 
                     set_format_strings(f_str("xxx (xx.x%)", distinct_n, distinct_pct))) %>% 
  set_distinct_by(USUBJID) %>% 
  Tplyr::add_layer(group_count(AESEV,by=AEDECOD) %>% 
                     set_format_strings(f_str("xxx (xx.x%)", distinct_n, distinct_pct))) %>% 
  set_distinct_by(USUBJID) %>% 
  add_total_group() %>%
  Tplyr::build() 

firstrow <- dt[dt$ord_layer_2==1,c('row_label1','ord_layer_1','ord_layer_2')]
firstrow$ord_layer_2 <- 0

dt <- bind_rows(dt, firstrow) %>% mutate(ord_layer_1=ifelse(row_label1=='Subjects with any Adverse Events',0,ord_layer_1))
dt <- dt %>% mutate(row_label1=ifelse(!is.na(row_label2), paste(' ', row_label2),row_label1)) %>% arrange(ord_layer_1,ord_layer_2,row_label2)
```

it results in 


<img width="630" alt="image" src="https://github.com/atorus-research/Tplyr/assets/83913148/70b6d5b2-fe63-4fb2-a955-d00130b0d09e">


one thing i am now struck with is about the page breaking by AEDECOD, which i am unable to understand as highlight in blue. 
could you please let me know your thoughts

**Comment by mstackhouse** [comment]
@jagadishkatam looks great! My plan is to introduce a function that can avoid that post processing. 

The page breaking is out of scope of Tplyr itself and depends on the package that you're using. What package are you using for display?

**Comment by jagadishkatam** [comment]
I am using the reporter package

**Comment by mstackhouse** [comment]
You would have to look into the documentation for reporter https://reporter.r-sassy.org/index.html
