### ISSUE TITLE
Way to use t.test instead of prop.test with add_risk_diff?

### ISSUE THREAD

**Issue by mrmorgan17** [atorus-research/Tplyr#149]
I am making clinical trails tables and I would like to conduct a t-test between the active vs the placebo group and display various results from that test in the table. It seems that this functionality is somewhat possible with the `add_risk_diff()` function but I noticed that is uses `prop.test()` as the default. I will want to use `t.test()` and I was just wondering if that was possible. 

If `add_risk_diff()` can't be modified, I'd appreciate it if someone could point me to alternative methodologies within Tplyr to perform a t-test between active and placebo and/or produce a custom summary to do such a task.

I am currently using version 1.1.0 of the Tplyr package.

Thank you

**Comment by mstackhouse** [comment]
This is technically relatively simple, but it'll take some re-evaluating of the way that the risk difference functions work themselves. We'll evaluate in the next update wave.

**Comment by mrmorgan17** [comment]
Good to know, thanks
