### ISSUE TITLE
Custom title for nested count summary

### ISSUE THREAD

**Issue by johanneswerner** [atorus-research/Tplyr#151]
### Description

I am trying to understand if it is possible to change the repeating value from the first column to something such as "Total".

I am using the [Nested Count Summaries example](https://github.com/vega/vega-lite/issues/8157)

```r
tplyr_table(adae, TRTA) %>%
  add_layer(
    group_count(vars(AEBODSYS, AEDECOD))
  ) %>%
  build() %>%
  head() %>% 
  kable()
```

Is it possible (and if so how) to change the value in `row_label2` for the "title of `row_label1` to change this to something like "Total" instead of repeating the value from `row_label1` (see box in image below)?

![Unsaved Image 1](https://github.com/atorus-research/Tplyr/assets/34099811/c5a57d93-26a2-4f97-9f7e-022c7282b20d)

**Comment by mstackhouse** [comment]
Hi @johanneswerner. We don't have a built in function to handle this. I think it would be easiest to handle this as a post-process. 

```r
dat %>%
  mutate(
    row_label2 = if_else(row_label1==row_label2, "Total", row_label2)
)
```
