### ISSUE TITLE
Tplyr and rlang 1.0.0

### ISSUE THREAD

**Issue by lionel-** [atorus-research/Tplyr#16]
Hello, I see in the revdep checks for the next version of rlang:

```
`Tplyr:::modify_nested_call(mean(c(1, 2, 3)))` threw an error with unexpected message.
Expected match: "`call` must be a quoted call"
Actual message: "`call` must be a defused call, not a number."
```

This is because you are testing for the contents of an error message generated in rlang:

```r
test_that("Call must be quoted", {
  expect_error(Tplyr:::modify_nested_call(mean(c(1,2,3))), "`call` must be a quoted call")
  c <- quo(tplyr_table(treat_var = Species))
  expect_silent(Tplyr:::modify_nested_call(c))
})
```

If you must monitor foreign errors, could you please do it in snapshots? See https://testthat.r-lib.org/articles/snapshotting.html

The great advantage of snapshots is that they only fail locally or in Github actions. This allows you to monitor the appearance of errors over time without causing check failures when things change upstream.

**Comment by elimillera** [comment]
Thanks for the issue and suggestion @lionel- .

@mstackhouse I can confirm this is an issue when I pull the dev version of rlang. I would agree with the above. Where ever we are using 'expect_error', we can replace it with 'expect_snapshot_error' so we don't cause upstream issues on CRAN.

**Comment by mstackhouse** [comment]
@elimillera that's fine with me - let's do it.

**Comment by mstackhouse** [comment]
@lionel thanks for these suggestions - Tplyr is off to CRAN.

**Comment by lionel-** [comment]
Thanks!
