### ISSUE TITLE
set_distinct_by() function is not considering set_pop_data() 

### ISSUE THREAD

**Issue by pamulra** [atorus-research/Tplyr#188]
I would like to create an AE table with the first three rows indicating the "Number of Subjects in the Population," "Number of Subjects with AE," and "Number of Subjects without AE." When I use the method below, the Numbers come from the target dataset instead of the population dataset. 

Can you please explain? 

```r
t <- tplyr_table(adae, TRT01A, where = c(AEBODSYS != " " & AEDECOD != " " & AEREL == "RELATED" )) %>%
  set_pop_data(adsl) %>% 
  set_pop_treat_var(TRT01A) %>%
  set_pop_where(SAFFL == "Y" ) %>%
  add_layer(
    group_count("Participants in population") %>%
      set_distinct_by(USUBJID) %>%
      set_format_strings(f_str('xx',n)) ) %>%
  
  add_layer(
  group_count("with one or more adverse events", where = !is.na(AEDECOD))  %>%
  set_distinct_by(USUBJID) %>%
  # set_format_strings(f_str('xx',n)) ) %>%
    set_format_strings(f_str('xx (xx.x%)', distinct_n, distinct_pct)) ) %>% 

  add_layer(
    group_count("with no adverse events", where = is.na(AEDECOD)) %>%
      set_distinct_by(USUBJID) %>%
      # set_format_strings(f_str('xx',n)) ) %>%
      set_format_strings(f_str('xx (xx.x%)', distinct_n, distinct_pct)) ) %>% 

  add_layer(
    group_count(vars(AEBODSYS, AEDECOD)) %>%
      set_format_strings(f_str('xx (xx.x%)', distinct_n, distinct_pct)) 
  )
```

**Comment by mstackhouse** [comment]
Hi @pamulra!

This is admittedly a bit complicated, because missing counts can mean two things:
- A record is present with a missing value
- There are no records for a particular subject

You're looking for the latter here, for which we have the function [`add_missing_subjects_row()`](https://atorus-research.github.io/Tplyr/reference/add_missing_subjects_row.html). 

You can achieve what you're looking for with the following example:

``` r
library(Tplyr)

tplyr_table(tplyr_adae, TRTA) %>%
  set_pop_data(tplyr_adsl) %>% 
  set_pop_treat_var(TRT01A) %>%
  add_layer(
    group_count("with one or more adverse events", where = !is.na(AEDECOD))  %>%
      set_distinct_by(USUBJID) %>%
      set_format_strings(f_str('xx (xx.x%)', distinct_n, distinct_pct)) %>% 
      add_missing_subjects_row() %>% 
      set_missing_subjects_row_label("with no adverse events")
  ) %>% 
  build()
#> # A tibble: 2 × 6
#>   row_label1          var1_Placebo var1_Xanomeline High…¹ var1_Xanomeline Low …²
#>   <chr>               <chr>        <chr>                  <chr>                 
#> 1 with one or more a… 21 (24.4%)   42 (50.0%)             42 (50.0%)            
#> 2 with no adverse ev… 65 (75.6%)   42 (50.0%)             42 (50.0%)            
#> # ℹ abbreviated names: ¹​`var1_Xanomeline High Dose`,
#> #   ²​`var1_Xanomeline Low Dose`
#> # ℹ 2 more variables: ord_layer_index <int>, ord_layer_1 <lgl>
```

<sup>Created on 2024-11-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

For more information you can see [this section](https://atorus-research.github.io/Tplyr/articles/denom.html#missing-subjects) of the Totals, Missings, and Denominators article.

**Comment by pamulra** [comment]
Thank you @mstackhouse. Using the add_missing_subjects_row(), I created a row with subjects in ADSL and not in ADAE. However, I need clarification on the functionality of the set_pop_data(), though we added the ADSL dataset using the set_pop_data(), the percentages of the AEs are calculated using the ADAE dataset. See the calling code below and output below.
Also, what's the best approach to create a row with a total count from both ADSL and ADAE? 

tplyr_adsl <- tplyr_adsl %>% rename(TRTA = TRT01A)

tplyr_table(tplyr_adae, TRTA) %>%
  set_pop_data(tplyr_adsl) %>%
  set_pop_treat_var(TRTA) %>%
  set_pop_where(SAFFL == "Y" ) %>%
  add_layer(
    group_count("Subjects in population") %>%
      set_distinct_by(USUBJID) %>%
      set_format_strings(f_str('xx',n)) ) %>%
  
  add_layer(
    group_count("with one or more adverse events", where = !is.na(AEDECOD))  %>%
      set_distinct_by(USUBJID) %>%
      set_format_strings(f_str('xx (xx.x%)', distinct_n, distinct_pct)) %>% 
      add_missing_subjects_row() %>% 
      set_missing_subjects_row_label("with no adverse events")
  ) %>% 
  add_layer(
    group_count(vars(AEBODSYS, AEDECOD))
  ) %>% 
build()

# A tibble: 25 × 8
   row_label1                     row_label2 var1_Placebo var1_Xanomeline High…¹
   <chr>                          <chr>      <chr>        <chr>                 
 1 Subjects in population          NA        " 47"        "111"                 
 2 with one or more adverse even…  NA        "21 (24.4%)" "42 (50.0%)"          
 3 with no adverse events          NA        "65 (75.6%)" "42 (50.0%)"          
 4 SKIN AND SUBCUTANEOUS TISSUE … "SKIN AND… " 47 (100.0… "111 (100.0%)"        
 5 SKIN AND SUBCUTANEOUS TISSUE … "   ACTIN… "  0 (  0.0… "  1 (  0.9%)"        
 6 SKIN AND SUBCUTANEOUS TISSUE … "   ALOPE… "  1 (  2.1… "  0 (  0.0%)"        
 7 SKIN AND SUBCUTANEOUS TISSUE … "   BLIST… "  0 (  0.0… "  2 (  1.8%)"        
 8 SKIN AND SUBCUTANEOUS TISSUE … "   COLD … "  3 (  6.4… "  0 (  0.0%)"        
 9 SKIN AND SUBCUTANEOUS TISSUE … "   DERMA… "  1 (  2.1… "  0 (  0.0%)"        
10 SKIN AND SUBCUTANEOUS TISSUE … "   DERMA… "  0 (  0.0… "  0 (  0.0%)

**Comment by mstackhouse** [comment]
It looks like you're using `n` instead of `distinct_n` in the "Subject in population" layer. Here's a comparison to understand the difference:

``` r
library(Tplyr)

tplyr_table(tplyr_adae, TRTA) %>%
  set_pop_data(tplyr_adsl) %>% 
  set_pop_treat_var(TRT01A) %>%
  # This is what you have
  add_layer(
    group_count("Subjects in population (bad)") %>%
      set_distinct_by(USUBJID) %>%
      set_format_strings(f_str('xx',n)) 
  ) %>% 
  # This is what it should be
  add_layer(
    group_count("Subjects in population (good)") %>%
      set_distinct_by(USUBJID) %>%
      set_format_strings(f_str('xx',distinct_n)) 
  ) %>% 
  build()
#> # A tibble: 2 × 6
#>   row_label1          var1_Placebo var1_Xanomeline High…¹ var1_Xanomeline Low …²
#>   <chr>               <chr>        <chr>                  <chr>                 
#> 1 Subjects in popula… " 47"        "111"                  "118"                 
#> 2 Subjects in popula… " 21"        " 42"                  " 42"                 
#> # ℹ abbreviated names: ¹​`var1_Xanomeline High Dose`,
#> #   ²​`var1_Xanomeline Low Dose`
#> # ℹ 2 more variables: ord_layer_index <int>, ord_layer_1 <lgl>
```

<sup>Created on 2024-11-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

'n' will always be non-distinct counts, which allows you to do things like display n, pct, and event rows. Any time you're considering distinct counts, use `distinct_n`, `distinct_pct`, or `distinct_total`.

**Comment by pamulra** [comment]
Thanks @mstackhouse . I have tried using distinct_n, but I don't see the right N and percentages for the AEs

tplyr_adsl <- tplyr_adsl %>% rename(TRTA = TRT01A)
tplyr_table(tplyr_adae, TRTA) %>%
  set_pop_data(tplyr_adsl) %>%
  set_pop_treat_var(TRTA) %>%
  set_pop_where(SAFFL == "Y" ) %>%
  add_layer(
    group_count("Subjects in population") %>%
      set_distinct_by(USUBJID) %>%
      set_format_strings(f_str('xx',distinct_n)) ) %>%
  
  add_layer(
    group_count("with one or more adverse events", where = !is.na(AEDECOD))  %>%
      set_distinct_by(USUBJID) %>%
      set_format_strings(f_str('xx (xx.x%)', distinct_n, distinct_pct)) %>% 
      add_missing_subjects_row() %>% 
      set_missing_subjects_row_label("with no adverse events")) %>% 
  add_layer(
    group_count(vars(AEBODSYS, AEDECOD)) %>%
      # set_nest_count(TRUE) %>%
      set_format_strings(f_str('xx (xx.x%)', distinct_n, distinct_pct)) 
  ) %>% 

build()
   row_label1                       row_label2 var1_Placebo var1_Xanomeline High…¹
   <chr>                            <chr>      <chr>        <chr>                 
 1 Subjects in population            NA        " 21"        " 42"                 
 2 with one or more adverse events   NA        "21 (24.4%)" "42 (50.0%)"          
 3 with no adverse events            NA        "65 (75.6%)" "42 (50.0%)"          
 4 SKIN AND SUBCUTANEOUS TISSUE DI… "SKIN AND… "47 (100.0%… "111 (100.0%)"        
 5 SKIN AND SUBCUTANEOUS TISSUE DI… "   ACTIN… " 0 ( 0.0%)" " 1 ( 0.9%)"          
 6 SKIN AND SUBCUTANEOUS TISSUE DI… "   ALOPE… " 1 ( 2.1%)" " 0 ( 0.0%)"          
 7 SKIN AND SUBCUTANEOUS TISSUE DI… "   BLIST… " 0 ( 0.0%)" " 2 ( 1.8%)"          
 8 SKIN AND SUBCUTANEOUS TISSUE DI… "   COLD … " 3 ( 6.4%)" " 0 ( 0.0%)"          
 9 SKIN AND SUBCUTANEOUS TISSUE DI… "   DERMA… " 1 ( 2.1%)" " 0 ( 0.0%)"          
10 SKIN AND SUBCUTANEOUS TISSUE DI… "   DERMA… " 0 ( 0.0%)" " 0 ( 0.0%)"

**Comment by mstackhouse** [comment]
Ah - in this example you haven't used `set_distinct_by(USUBJID)` on the AEBODSYS/AEDECOD layer.

``` r
library(Tplyr)
tplyr_table(tplyr_adae, TRTA) %>%
  set_pop_data(tplyr_adsl) %>%
  set_pop_treat_var(TRT01A) %>%
  set_pop_where(SAFFL == "Y") %>%
  add_layer(
    group_count(vars(AEBODSYS, AEDECOD)) %>%
      set_distinct_by(USUBJID) %>% # You were missing this line
      set_format_strings(f_str('xx (xx.x%)', distinct_n, distinct_pct))
  ) %>%
  build()
#> # A tibble: 22 × 8
#>    row_label1                     row_label2 var1_Placebo var1_Xanomeline High…¹
#>    <chr>                          <chr>      <chr>        <chr>                 
#>  1 SKIN AND SUBCUTANEOUS TISSUE … "SKIN AND… "21 (24.4%)" "42 (50.0%)"          
#>  2 SKIN AND SUBCUTANEOUS TISSUE … "   ACTIN… " 0 ( 0.0%)" " 1 ( 1.2%)"          
#>  3 SKIN AND SUBCUTANEOUS TISSUE … "   ALOPE… " 1 ( 1.2%)" " 0 ( 0.0%)"          
#>  4 SKIN AND SUBCUTANEOUS TISSUE … "   BLIST… " 0 ( 0.0%)" " 1 ( 1.2%)"          
#>  5 SKIN AND SUBCUTANEOUS TISSUE … "   COLD … " 1 ( 1.2%)" " 0 ( 0.0%)"          
#>  6 SKIN AND SUBCUTANEOUS TISSUE … "   DERMA… " 1 ( 1.2%)" " 0 ( 0.0%)"          
#>  7 SKIN AND SUBCUTANEOUS TISSUE … "   DERMA… " 0 ( 0.0%)" " 0 ( 0.0%)"          
#>  8 SKIN AND SUBCUTANEOUS TISSUE … "   DRUG … " 1 ( 1.2%)" " 0 ( 0.0%)"          
#>  9 SKIN AND SUBCUTANEOUS TISSUE … "   ERYTH… " 9 (10.5%)" "14 (16.7%)"          
#> 10 SKIN AND SUBCUTANEOUS TISSUE … "   HYPER… " 2 ( 2.3%)" " 8 ( 9.5%)"          
#> # ℹ 12 more rows
#> # ℹ abbreviated name: ¹​`var1_Xanomeline High Dose`
#> # ℹ 4 more variables: `var1_Xanomeline Low Dose` <chr>, ord_layer_index <int>,
#> #   ord_layer_1 <dbl>, ord_layer_2 <dbl>
```

<sup>Created on 2024-11-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

An option to avoid this in the future is to use `set_distinct_by()` on the table level instead of the layer level. 

``` r
library(Tplyr)
tplyr_table(tplyr_adae, TRTA) %>%
  set_pop_data(tplyr_adsl) %>%
  set_pop_treat_var(TRT01A) %>%
  set_distinct_by(USUBJID) %>% 
  add_layer(
    group_count("Subjects in population") %>%
      set_format_strings(f_str('xx',distinct_n)) ) %>%
  add_layer(
    group_count("with one or more adverse events", where = !is.na(AEDECOD)) %>%
      set_format_strings(f_str('xx (xx.x%)', distinct_n, distinct_pct)) %>%
      add_missing_subjects_row() %>%
      set_missing_subjects_row_label("with no adverse events")) %>%
  add_layer(
    group_count(vars(AEBODSYS, AEDECOD)) %>%
      set_nest_count(TRUE) %>% 
      set_format_strings(f_str('xx (xx.x%)', distinct_n, distinct_pct))
  ) %>%
  build()
#> # A tibble: 25 × 7
#>    row_label1         var1_Placebo var1_Xanomeline High…¹ var1_Xanomeline Low …²
#>    <chr>              <chr>        <chr>                  <chr>                 
#>  1 "Subjects in popu… " 21"        " 42"                  " 42"                 
#>  2 "with one or more… "21 (24.4%)" "42 (50.0%)"           "42 (50.0%)"          
#>  3 "with no adverse … "65 (75.6%)" "42 (50.0%)"           "42 (50.0%)"          
#>  4 "SKIN AND SUBCUTA… "21 (24.4%)" "42 (50.0%)"           "42 (50.0%)"          
#>  5 "   ACTINIC KERAT… " 0 ( 0.0%)" " 1 ( 1.2%)"           " 0 ( 0.0%)"          
#>  6 "   ALOPECIA"      " 1 ( 1.2%)" " 0 ( 0.0%)"           " 0 ( 0.0%)"          
#>  7 "   BLISTER"       " 0 ( 0.0%)" " 1 ( 1.2%)"           " 5 ( 6.0%)"          
#>  8 "   COLD SWEAT"    " 1 ( 1.2%)" " 0 ( 0.0%)"           " 0 ( 0.0%)"          
#>  9 "   DERMATITIS AT… " 1 ( 1.2%)" " 0 ( 0.0%)"           " 0 ( 0.0%)"          
#> 10 "   DERMATITIS CO… " 0 ( 0.0%)" " 0 ( 0.0%)"           " 1 ( 1.2%)"          
#> # ℹ 15 more rows
#> # ℹ abbreviated names: ¹​`var1_Xanomeline High Dose`,
#> #   ²​`var1_Xanomeline Low Dose`
#> # ℹ 3 more variables: ord_layer_index <int>, ord_layer_1 <dbl>,
#> #   ord_layer_2 <dbl>
```

<sup>Created on 2024-11-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by pamulra** [comment]
Thank you, @mstackhouse. That helped me get the correct percentage. One last clarification regarding the "Subjects in population": I see all our examples, including your last one. We need to correct the counts. The count should be big N and from ADSL. However, it's taking the count from typlr_adae. Typically, that count is the sum of 2nd and 3rd-row counts. Do you have any thoughts on that?

**Comment by mstackhouse** [comment]
You can use the value `distinct_total` instead of `distinct_n` to get that value. 

https://atorus-research.github.io/Tplyr/articles/general_string_formatting.html#format-strings
