### ISSUE TITLE
Infinities produced in min/max when no obs variable when using multiple targets

### ISSUE THREAD

**Issue by elimillera** [atorus-research/Tplyr#21]
If multiple target variables are used in `group_desc()`, and all observations for the target variable are null, Inf and -Inf may be presented for min and max values. 

Responsibility of where this is corrected isn't immediately clear. We don't want to by default mask infinity values returned by summary functions, and we don't want to produced unexpected results from our summary functions.

**Comment by mstackhouse** [comment]
Closed via #158
