### ISSUE TITLE
Update documentation for `set_indentation`

### ISSUE THREAD

**Issue by elimillera** [atorus-research/Tplyr#23]
Update count vignette where it says:
The default indentation used will be 3 spaces, but as you can see here - you can set the indentation however you like using set_indentation().
Update To:
The default indentation used will be 3 spaces, but as you can see here - you can set the indentation however you like using set_indentation().

Also update the default for set_indentation to "   "(three spaces) to make it clear what the default is

**Comment by mstackhouse** [comment]
@elimillera am I missing what the suggested change in that text is?
