### ISSUE TITLE
devel branch not supporting denom/total as formatable value for count layers

### ISSUE THREAD

**Issue by mstackhouse** [atorus-research/Tplyr#61]
### Prerequisites

For more information, see the `CONTRIBUTING` guide.

### Description

The current dev branch isn't respecting `denom` or `total` as a valid name within an `f_str()` in `set_format_strings()`

### Steps to Reproduce (Bug Report Only)

```r
t <- tplyr_table(mtcars, cyl) %>% 
  add_layer(
     group_count(gear) %>% 
        set_format_strings('xx (xx.x) xx', n, pct, denom)
   ) 
# Error: In `set_format_string` entry 1 is not an `f_str` object. All assignmentes made within `set_format_string` must be made using the function `f_str`. See the `f_str` documentation.
```

**Expected behavior:** [What you expected to happen]

If you use `get_numeric_data()`, the denom is available as total. Count layers need a valid name available to use to add denom to the formatted string.

**Actual behavior:** [What actually happened]

Error above

### Versions

This is using the current devel branch

**Comment by elimillera** [comment]
@mstackhouse This is working in devel:
```
t <- tplyr_table(mtcars, cyl) %>% 
  add_layer(
    group_count(gear) %>% 
      set_format_strings(f_str('xx (xx.x) xx', n, pct, total))
  ) %>%
  build()
```
