### ISSUE TITLE
Make vignette data easily available

### ISSUE THREAD

**Issue by thebioengineer** [atorus-research/Tplyr#62]
https://github.com/atorus-research/Tplyr/blob/dabbcbff6c09d455a9152d8f2c5689f875182335/vignettes/desc.Rmd#L24

Hey, could you all make this data available to load from your package directly? Drop the RDA into the `data` folder and add descriptions into a .R script for them, and it would make replicating your vignettes much easier!

**Comment by mstackhouse** [comment]
Thanks, @thebioengineer. We can squeeze that in with the next release.
