### ISSUE TITLE
Formatting issue in "table" vignette 

### ISSUE THREAD

**Issue by zittau17** [atorus-research/Tplyr#7]
In the “table” vignette, under “Additional Treatment Groups” . . .
![image](https://user-images.githubusercontent.com/45572279/93075317-3aefde00-f64b-11ea-92a5-b014f190805d.png)

**Comment by mstackhouse** [comment]
Thanks for reporting! We'll take care of it.

**Comment by elimillera** [comment]
Rmd file was missing a new line after `kable` function call. This has been resolved. Thank you for reporting!
