### ISSUE TITLE
Question issue with duplicate lower level term counting

### ISSUE THREAD

**Issue by aehmann-gsk** [atorus-research/Tplyr#75]
This may be a user issue and I was able to easily overcome this by tweaking my input dataset slightly and then stripping it off.  Please just let me know if I have made an error in calling.

When doing count (frequencies),  However, this could cause a similar issue with something like questionnaires where you may need to create a layer for each individual question as I would expect at times the results being used in the frequency counts to be duplicated across PARAMCDs.  

If the `AEDECOD` is not unique across all `AESOC`, the counts were erroneous.

Below is an example using CDISC pilot data - depending on the `mutate` statement, you get different results for the Any Event row and it is only correct when `Any Event` is unique per `AESOC`.

(Note - per our standards, the counts at the `AESOC` level are presented on their own line hence adding in the Any Event row for each `AESOC`)

```
# Subsetting and small dataset manipulations to get it ready for analysis
adae_ <- adae %>% 
# Get correct counts
#  mutate(AEDECOD = paste0("Any event|", AESOC)) %>% 
# Get erroneous counts for Any event
  mutate(AEDECOD = "Any event") %>% 
  union_all(adae) %>% 
  left_join(select(adsl, USUBJID, TRT01AN, TRT01A), by = "USUBJID") %>% 
  filter(TRTEMFL == "Y") 

# Character formatted table for rendering table outputs
# set_format_strings should be set to the appropriate decimals needed for the table
dddata_table_object_character <- tplyr_table(adae_, TRT01AN, where = SAFFL == "Y") %>% 
  add_total_group() %>%
  set_pop_data(adsl) %>% 
  add_layer(group_count('ANY EVENT') %>%
              set_distinct_by(USUBJID) %>%
              # set_order_count_method("bycount") %>%
              set_format_strings(f_str("xxx (xxx.x%)", distinct_n, distinct_pct))) %>%
  add_layer(group_count(vars(AESOC, AEDECOD))  %>%
              set_distinct_by(vars(USUBJID)) %>%
              set_format_strings(f_str("xxx (xxx.x%)", distinct_n, distinct_pct)))
```

**Comment by mstackhouse** [comment]
Closed by #172
