### ISSUE TITLE
build() error when grouping variable (argument cols) has fewer categories than pop data and set_distinct_by() is introduced.

### ISSUE THREAD

**Issue by yangwenghou123** [atorus-research/Tplyr#81]
### Description
(Please refer to the test codes following)
When grouping variable "part" in "tar" doesn't have the value "b" which appears in pop data "sl" and set_distinct_by() is introduced, there will be an error preventing from executing build().

Is there a bug, or something I have missed?

tar <- data.frame(id =1,
                  trt=1,
                  part="a",
                  q=1,
                  stringsAsFactors =FALSE)
sl <- data.frame(id=1:2,trt=1:2, part = letters[1:2],
                 stringsAsFactors =FALSE)

res <- tplyr_table(tar, trt, cols= part)
pop_data(res) <- sl
set_pop_treat_var(res, trt)
res <- res %>% 
  add_total_group(group_name = "Total") %>%
  add_layer(
    group_count(q)%>% 
      set_distinct_by(id) %>% 
      add_total_row()
  ) 

res <- res %>% build()

Error in `filter()`:
! Problem while computing `..2 = part == structure(1L, .Label = "a", class = "factor")`.
Caused by error in `Ops.factor()`:
! level sets of factors are different

### Versions

R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
system code page: 936

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openxlsx_4.2.5   dplyr_1.0.9      rtables_0.5.1    formatters_0.3.2 magrittr_2.0.3   Tplyr_0.4.4

**Comment by mstackhouse** [comment]
Hi @yangwenghou123 - the latest update on the devel branch (#82) resolves this issue. This will trickle into the Tplyr 1.0.0 release that we're currently working towards. 

You can install that branch using `devtools::install_github("https://github.com/atorus-research/Tplyr.git", ref="devel")`. Let me know if you have any issues.
