### ISSUE TITLE
Typo in Typlyr Table Properties vignette

### ISSUE THREAD

**Issue by asbates** [atorus-research/Tplyr#86]
### Description

In the Population Data section, the 'the' in the following sentence should be 'they':

["In CDISC standards, datasets like adae only contain adverse events when the occur"](https://github.com/atorus-research/Tplyr/blob/dabbcbff6c09d455a9152d8f2c5689f875182335/vignettes/table.Rmd#L90)

**Comment by elimillera** [comment]
Closed with PR #89
