### ISSUE TITLE
1.0.0 Doc Updates

### ISSUE THREAD

**Issue by mstackhouse** [atorus-research/Tplyr#88]
- [x] README
- [x] NEWS.md
- [x] Set package to stable
- [x] #70
- [x] #56 
- [x] Add lifecycle badges
- [x] `set_numeric_threshold()` labelled experimental
- [x] Update package version
- [x] pkgdown updates
- [x] #69 
- [x] #86 
- [x] #38
- [x] #91

**Comment by elimillera** [comment]
Closed with PR #89
