### ISSUE TITLE
Alternate rounding option?

### ISSUE THREAD

**Issue by Robert-Krajcik** [atorus-research/Tplyr#9]
Hi Eli and Mike,

I am looking at using Tplyr to validate tables created in SAS

I am not having issues comparing medians and other percentiles because I am using
`options(tplyr.quantile_type = 3)`

But sometimes the data generated by the `group_count()` layer
`set_count_layer_formats(n_counts = f_str("xx (xxx%)", n, pct))`
is off by a digit.  And `Proc Compare` throws it out, causing it to "fail" validation.

I had been reading this blog by Ali Dootson
[TFL programming in R versus SAS](https://www.d-wise.com/blog/tfl-programming-in-r-versus-sas)

And found a function they wrote that emulates SAS rounding.
```{r, eval=FALSE}
ut_round <- function(x, n=0)
{
 # x is the value to be rounded
 # n is the precision of the rounding
 scale <- 10^n
 y <- trunc(x * scale + sign(x) * 0.5) / scale
 # Return the rounded number
 return(y)
}
```
I have been using this to post-process the Tplyr tibble created and update the `nnn (nnn%)` strings
so I can get `Proc Compare` to accept the results.

Any chance you could come up with an alternate rounding option?
Perhaps something like
`options(tpylr.rounding = {default|SAS}`?

Right now I am only seeing the issue with percentages generated in `group_count()`

Thanks so much!
Robert

**Comment by elimillera** [comment]
Hey @Robert-Krajcik,

We made the decision not to try to "force" R to be exactly the same as SAS. However I do see how that would be useful in this case. I think `options(tplyr.rounding = {IEC | IBM})` would be a good option to have for those who need it. I'll add it to the backlog for us to tackle in a future release.

Thanks for the suggestion!
Eli

**Comment by elimillera** [comment]
@Robert-Krajcik 

We are looking at another release of Tplyr. Do you have an example we can use to test the different rounding?

**Comment by Robert-Krajcik** [comment]
Sure I will post a small reprex for you here.

**Comment by Robert-Krajcik** [comment]
This is an example to illustrate the differences
```{r, eval=FALSE}
row_num <- seq(1:2000)
trta = ifelse(row_num <= 1000, "Placebo", "ThisDrg")
gender = ifelse(between(row_num, 1, 485), "F",
                ifelse(between(row_num, 1001, 1525), "F", "M"))
adsl <- tibble(trta, gender)

options(
  tplyr.count_layer_default_formats =
    list(n_counts = f_str("xxx (xxx%)", n, pct)
    )
)
  
tabl <- tplyr_table(adsl, trta) %>% 
  add_total_group(group_name = "Total") %>% 
  add_layer(
    group_count(gender, by = "Gender") 
  ) %>% 
build()
```
Results in
```{r, eval=FALSE}
> tabl
# A tibble: 2 x 8
  row_label1 row_label2 var1_Placebo var1_ThisDrg var1_Total  ord_layer_index ord_layer_1 ord_layer_2
  <chr>      <chr>      <chr>        <chr>        <chr>                 <int>       <int>       <dbl>
1 Gender     F          485 ( 48%)   525 ( 52%)   1010 ( 50%)               1           1           1
2 Gender     M          515 ( 52%)   475 ( 48%)   990 ( 50%)                1           1           2
```

equivalent SAS program, using Proc Tabulate
```{r, eval=FALSE}
data test;
trta = "Placebo"; gender = "F"; wgt = 485; output;
trta = "Placebo"; gender = "M"; wgt = 515; output;
trta = "ThisDrg"; gender = "F"; wgt = 525; output;
trta = "ThisDrg"; gender = "M"; wgt = 475; output;
run;

ods listing; ods noresults; options nocenter;

proc format;                           
   picture mypct (round) low-high='009%';
run; 

proc tabulate data=test format=8.2;
 class gender trta;
 freq wgt;
 table gender, (trta all="total")*(n*f=4.0 colpctn="pct"*f=mypct.) /RTS=10;  
run;
```
which generates:
```{r, eval=FALSE}
----------------------------------------
|        |       trta        |         |
|        |-------------------|         |
|        | Placebo | ThisDrg |  total  |
|        |---------+---------+---------|
|        | N  |pct | N  |pct | N  |pct |
|--------+----+----+----+----+----+----|
|gender  |    |    |    |    |    |    |
|--------|    |    |    |    |    |    |
|F       | 485| 49%| 525| 53%|1010| 51%|
|--------+----+----+----+----+----+----|
|M       | 515| 52%| 475| 48%| 990| 50%|
----------------------------------------
```

**Comment by elimillera** [comment]
Hello @Robert-Krajcik,

An option has been added to Tplyr 0.4.0 for this. `options(tplyr.IBMRounding = TRUE)` will simulate the rounding you are trying to recreate. Its up to date on our github so `remotes::install_github("atorus-research/Tplyr")` will install the development version.

Thanks again for the suggestion!
